package com.geoida.progeo;


import android.annotation.SuppressLint;
import android.content.res.ColorStateList;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.GooglePlayServicesUtil;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.MapView;
import com.google.android.gms.maps.MapsInitializer;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.model.MapStyleOptions;

/**
 * Created by Kamil on 23.03.2017.
 * Fragment showing statistics generated by GoogleApis and OSM.
 */

// Wiktor - I added strictfp to be sure that all math operation are correct
public strictfp class FragmentSummary extends Fragment implements OnMapReadyCallback {

    MapView mapView;
    GoogleMap map;

    private TextView Distance;
    private TextView Slope;
    private ProgressBar RouteType;
    private ProgressBar CrossRoads;
    private ProgressBar Greenlevel;

    private boolean routeSaved = false;

    @Override
    public void onDetach() {
        super.onDetach();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }


    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_summary, container, false);

        try {
            MapsInitializer.initialize(getActivity());
        } catch (Exception e) {
        }
        switch (GooglePlayServicesUtil.isGooglePlayServicesAvailable(getActivity())) {
            case ConnectionResult.SUCCESS:
                mapView = (MapView) v.findViewById(R.id.map_summary);
                mapView.onCreate(savedInstanceState);
                mapView.getMapAsync(this);
                break;
            default:
                Toast.makeText(getActivity(), GooglePlayServicesUtil.isGooglePlayServicesAvailable(getActivity()), Toast.LENGTH_SHORT).show();
        }



        Distance = (TextView) v.findViewById(R.id.SummaryDistanceValue);
        Slope = (TextView) v.findViewById(R.id.SummaryElevationValue);
        RouteType = v.findViewById(R.id.routesQualityBar);
        CrossRoads = v.findViewById(R.id.crossroadsBar);
        Greenlevel = v.findViewById(R.id.greenLevelBar);
        return v;
    }

    public void notifyRouteSaved(){routeSaved = true;}

    public void notifyRouteNotSaved(){
        routeSaved = false;}

    @Override
    public void onPause() {
        super.onPause();
        routeSaved = false;
        if(mapView != null)
            mapView.onPause();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        routeSaved = false;
        if(mapView != null)
            mapView.onDestroy();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        if(mapView != null)
            mapView.onSaveInstanceState(outState);
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        if(mapView != null)
            mapView.onLowMemory();
    }

    @Override
    public void onResume() {
        super.onResume();
        if(mapView != null)
            mapView.onResume();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
    }

    @SuppressLint("MissingPermission")
    @Override
    public void onMapReady(GoogleMap googleMap) {
        map = googleMap;

       // map.setMyLocationEnabled(true);

        ((MainActivity)getActivity()).showRouteInformation(map,Distance,Slope,RouteType,CrossRoads,Greenlevel);
    }
}
